# Generated by Django 2.2.16 on 2022-12-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20221217_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку рецепта', null=True, upload_to='recipes/', verbose_name='Картинка'),
        ),
    ]
