# Generated by Django 2.2.16 on 2022-12-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20221217_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ('id',), 'verbose_name': 'Количество ингредиентов'},
        ),
    ]
