# Generated by Django 2.2.16 on 2022-12-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_auto_20221218_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ('id',), 'verbose_name': 'Количество ингредиентов', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
    ]
